chore: add a default to setup to create an admin keycloak user
defenseunicorns/uds-common pull request #111
Opened 2024-04-18 01:02 UTC by Racer159

This adds the option to automatically create a keycloak admin user

2024-04-19 01:40 UTC, zachariahmiller requested changes
Not sure on the embedded `uds zarf yq` availability yet, but the email should probably change 🤔

2024-04-19 01:40 UTC, zachariahmiller commented on tasks/setup.yaml
> +              "email": "doug@defenseunicorns.com",
```suggestion
              "email": "doug@uds.dev",
```

I'd assume this makes more sense, but 🤷

2024-04-19 01:40 UTC, zachariahmiller commented on tasks/setup.yaml
> +            --data-urlencode "grant_type=password" | yq .access_token)
```suggestion
            --data-urlencode "grant_type=password" | ./ uds zarf tools yq .access_token)
```

I guess im not certain if we can do this yet. If not please ignore.

2024-04-19 01:40 UTC, zachariahmiller commented on tasks/setup.yaml
> +            --header "Authorization: Bearer ${KEYCLOAK_ADMIN_TOKEN}" | yq '.[] | select(.displayName == "Conditional OTP") | .id')
```suggestion
            --header "Authorization: Bearer ${KEYCLOAK_ADMIN_TOKEN}" | ./uds zarf tools yq '.[] | select(.displayName == "Conditional OTP") | .id')
```
same comment as the other one

2024-04-19 02:03 UTC, zachariahmiller approved these changes
:shipit:

2024-04-19 15:04 UTC, merged

2024-10-22 20:56 UTC, UncleGedd commented
You glorious 🦄 s. Here I am 6 months later wondering how I'm going test SSO in UDS Runtime, and I find this 🤌