Add Apache-2.0 license ADR
defenseunicorns/uds-common pull request #163
Opened 2024-06-29 01:31 UTC by daveworth

2024-07-02 20:51 UTC, zachariahmiller commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +business lately moving towards source-available licenses after gaining scale for
businesses

2024-07-02 21:01 UTC, zachariahmiller reviewed
@daveworth left a couple comments/nits. Also i think since this is an ADR regarding licensing and doesnt impacts the functionality of the code in this repo the semantic commit could be something like `docs(adr)` instead of `feat(adr)` as to not trigger a minor release of the code base.

2024-07-03 00:20 UTC, daveworth commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +business lately moving towards source-available licenses after gaining scale for
```suggestion
businesses lately moving towards source-available licenses after gaining scale for
```

2024-07-03 00:21 UTC, daveworth commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +Some of our competitors may take UDS, slap their logo on it, and sell
```suggestion
Could some of our competitors take UDS, slap their logo on it, and sell
```

2024-07-03 00:21 UTC, daveworth commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +it/underbid us in some cases? Absolutely. We acknowledge that is possible.  But
```suggestion
it and/or underbid us in some cases? Absolutely. We acknowledge that is possible.  But
```

2024-07-03 15:24 UTC, zachariahmiller submitted a review, later dismissed
LGTM barring any additional changes @jeff-mccoy or @Racer159 might suggest.

2024-07-03 17:47 UTC, daveworth commented
@Racer159 *thank you* for the updated title.  I was just noting yesterday that I don't like `chore` as the conventional commit message around docs and @Noxsios reminded me that `docs` is a first-class citizen of the ecosystem!

2024-07-04 04:19 UTC, Racer159 requested changes
(decided to take a second look)

2024-07-04 04:19 UTC, Racer159 commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +our hyper-scaler equivalents, they are in the same markets with considerable
```suggestion
our hyper-scaler equivalents, they are in the same markets with considerably
```

2024-07-04 04:19 UTC, Racer159 commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +other successful defense contractors in particular, is really around out ability
```suggestion
other successful defense contractors in particular, is really around our ability
```

2024-07-04 04:19 UTC, Racer159 commented on docs/adrs/0002-apache-2.0-for-all-uds-products.md
> +mission impact is still what drives us, we are choosing to keeping everything
```suggestion
mission impact is still what drives us, we are choosing to keep everything
```

2024-07-04 14:45 UTC, daveworth commented
updated! Thanks @Racer159

2024-07-12 16:20 UTC, Racer159 approved these changes

2024-07-12 16:21 UTC, merged