feat: add task for determining target repo based on flavor
defenseunicorns/uds-common pull request #188
Opened 2024-07-25 17:03 UTC by marshall007

Based on https://github.com/defenseunicorns/uds-core/pull/585

2024-07-26 21:28 UTC, Racer159 requested changes

2024-07-26 21:28 UTC, Racer159 commented on tasks/utils.yaml
> +          repo="${repo}/uds"
this should be an input passed up and out of both pull / publish

2024-07-26 21:29 UTC, Racer159 commented on tasks/utils.yaml
> +          repo="${repo}/uds"
for these people: https://github.com/defenseunicorns/leapfrogai/pkgs/container/packages%2Fleapfrogai%2Fleapfrogai-api

2024-07-29 19:49 UTC, Racer159 approved these changes

2024-07-29 19:50 UTC, zachariahmiller approved these changes
🚀

2024-07-29 20:31 UTC, merged