feat: provide uds-releaser option for publishing uds packages
defenseunicorns/uds-common pull request #341
Opened 2024-11-18 22:55 UTC by corang

## Description

...

## Checklist before merging

- [ ] ADR proposed if making an architectural change to the repo
- [ ] Tests run, docs added or updated as needed

2024-12-04 22:06 UTC, Racer159 requested changes

2024-12-04 22:06 UTC, Racer159 commented on .github/workflows/release-uds.yaml
> +# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
We should just cutover the existing release workflow.

2024-12-04 22:06 UTC, Racer159 commented on tasks.yaml
> +  - release: ./tasks/release.yaml
```suggestion
```

2024-12-06 01:16 UTC, Racer159 commented on releaser.yaml
> +    version: 1.27.3
is it possible to renovate these with a `# renovate` comment?

2024-12-06 14:35 UTC, corang commented
Not super confident in those renovate comments but I don't know how to see if they're working

2024-12-06 16:29 UTC, Racer159 commented
> Not super confident in those renovate comments but I don't know how to see if they're working

You can easily test in a fork:

https://github.com/Racer159/uds-common/commit/5af5a0a1c6f71374941a18b70cd680b16234e5c5

You just have to enable renovate for your personal repo and drop the host rules:

https://github.com/Racer159/uds-common/commit/cdb40a521d8e33b8b9f550674ba13b9813e17474#diff-7ad11411d2424c8b7004545af4a91293b3a953c25e697b262f27a57bdba2b414L31

And point the renovate.json to the one in your repo:

https://github.com/Racer159/uds-common/commit/6bbae79f8c7b1c267d0b29f315d9fb33938a5dcf

Then enable issues in settings and look through the dashboard: https://github.com/Racer159/uds-common/issues/3 or go through PRs: https://github.com/Racer159/uds-common/pull/13

2024-12-06 16:31 UTC, Racer159 requested changes

2024-12-06 16:31 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +  version: 1.27.3
```suggestion
  version: dev
```

2024-12-06 16:31 UTC, Racer159 commented on bundle/uds-bundle.yaml
> +    ref: 1.27.3
```suggestion
    ref: dev
```

2024-12-06 16:31 UTC, Racer159 commented on zarf.yaml
> +  version: 1.27.3
```suggestion
  version: dev
```

2024-12-06 16:46 UTC, Racer159 approved these changes

2024-12-06 16:53 UTC, merged